# Generated by Django 5.1.7 on 2025-04-18 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('explicit', models.BooleanField()),
                ('person_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_relationships_a', to='main.person')),
                ('person_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_relationships_b', to='main.person')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('person_a', 'person_b'), name='unique_contact_connection')],
            },
        ),
    ]
