# Generated by Django 5.1.7 on 2025-04-24 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contactconnection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('info', 'Info'), ('account_connection', 'Account Connection'), ('ledger_connection', 'Ledger Connection'), ('balance_approve', 'Balance Approve')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('denied', 'Denied'), ('obsolete', 'Obsolete')], default='pending', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('balance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.paymentbalance')),
                ('ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.ledger')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_notification', to='main.person')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_notification', to='main.person')),
            ],
        ),
    ]
